In [2]:
import pandas as pd

In [2]:
df = pd.read_csv("games.csv")
df.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [3]:
print("Dimensions :", df.shape)
print("Colonnes :", df.columns.tolist())

df.info()

Dimensions : (125855, 39)
Colonnes : ['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'DiscountDLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']
<class 'pandas.DataFrame'>
Index: 125855 entries, 2539430 to 4247310
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       125854 non-null  str
 1   Name                        125855 non-null  str
 2   Release date                125855 non-null  str
 3   Estimated owners            125855 non-null  int64
 4   Peak CCU                    125855 non-null  int64
 5   Required age                125855 non-null  float64
 6   Price                       125855 non-null  int64
 7   DiscountDLC count           125855 non-null  int64
 8   About the game              117393 non-null  str
 9   Supported languages         125855 non-null  str
 10  Full audio languages        125855 non-null  str
 11  Reviews                     12181 non-null   str
 12  Header image                125774 non-null  str
 13  Website                     50520 non-null   str
 14  Support url                 55295 non-null   str
 15  Support email               103225 non-null  str
 16  Windows                     125855 non-null  bool
 17  Mac                         125855 non-null  bool
 18  Linux                       125855 non-null  bool
 19  Metacritic score            125855 non-null  int64
 20  Metacritic url              4258 non-null    str
 21  User score                  125855 non-null  int64
 22  Positive                    125855 non-null  int64
 23  Negative                    125855 non-null  int64
 24  Score rank                  40 non-null      float64
 25  Achievements                125855 non-null  int64
 26  Recommendations             125855 non-null  int64
 27  Notes                       23310 non-null   str
 28  Average playtime forever    125855 non-null  int64
 29  Average playtime two weeks  125855 non-null  int64
 30  Median playtime forever     125855 non-null  int64
 31  Median playtime two weeks   125855 non-null  int64
 32  Developers                  117406 non-null  str
 33  Publishers                  116933 non-null  str
 34  Categories                  116889 non-null  str
 35  Genres                      117432 non-null  str
 36  Tags                        83353 non-null   str
 37  Screenshots                 119828 non-null  str
 38  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(14), str(19)
memory usage: 35.9 MB

In [8]:
df["Estimated owners"].value_counts(dropna=False)

Estimated owners
0       106175
1         6529
2         2506
3         1428
4          931
         ...
4696         1
2928         1
352          1
1050         1
1756         1
Name: count, Length: 1110, dtype: int64

In [9]:
df.isnull().sum()

AppID                              1
Name                               0
Release date                       0
Estimated owners                   0
Peak CCU                           0
Required age                       0
Price                              0
DiscountDLC count                  0
About the game                  8462
Supported languages                0
Full audio languages               0
Reviews                       113674
Header image                      81
Website                        75335
Support url                    70560
Support email                  22630
Windows                            0
Mac                                0
Linux                              0
Metacritic score                   0
Metacritic url                121597
User score                         0
Positive                           0
Negative                           0
Score rank                    125815
Achievements                       0
Recommendations                    0
Notes                         102545
Average playtime forever           0
Average playtime two weeks         0
Median playtime forever            0
Median playtime two weeks          0
Developers                      8449
Publishers                      8922
Categories                      8966
Genres                          8423
Tags                           42502
Screenshots                     6027
Movies                        125855
dtype: int64

In [32]:

# Définir les limites des 5 catégories
limites = [
    -1,1, 100, 2000, 10000,
    100000, float("inf")
]

noms = [
    "Nulle",
    "Très faible",
    "Faible",
    "Moyenne",
    "Élevée",
    "Très élevée"
]

# Attribuer une catégorie à chaque jeu
df["Categorie owners"] = pd.cut(
    df["Estimated owners"],
    bins=limites,
    labels=noms
)

df["Categorie owners"].value_counts(normalize=True) * 100

Categorie owners
Nulle          89.550673
Très faible     8.899925
Faible          1.303087
Moyenne         0.170832
Élevée          0.069127
Très élevée     0.006357
Name: proportion, dtype: float64

In [13]:
df["categorie_owners"].value_counts(normalize=True) * 100

Series([], Name: proportion, dtype: float64)

In [3]:
df = pd.read_csv("vgsales.csv")
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [8]:
df["Eu_Sales"].value_counts(dropna=False)

KeyError: 'Eu_Sales'

In [6]:
print("Dimensions :", df.shape)
print("Colonnes :", df.columns.tolist())

df.info()

Dimensions : (16598, 11)
Colonnes : ['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']
<class 'pandas.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  str
 2   Platform      16598 non-null  str
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  str
 5   Publisher     16540 non-null  str
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 1.4 MB

In [7]:
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [29]:

# Définir les limites des 5 catégories
limites = [
    -1,0.001, 0.01, 0.1, 1,
    20, float("inf")
]

noms = [
    "<1 000",
    "1 000-10 000",
    "10 000-100 000 ",
    "100 000-1M",
    "1M-20M",
    "20M<"
]

# Attribuer une catégorie à chaque jeu
df["Categorie owners"] = pd.cut(
    df["EU_Sales"],
    bins=limites,
    labels=noms
)

df["Categorie owners"].value_counts(normalize=True) * 100

Categorie owners
<1 000             34.522232
10 000-100 000     30.750693
100 000-1M         22.882275
1 000-10 000        9.013134
1M-20M              2.825642
20M<                0.006025
Name: proportion, dtype: float64