In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv("vgsales.csv")
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [21]:
# Dimensions du dataset
print("Nombre de lignes :", df.shape[0])
print("Nombre de colonnes :", df.shape[1])

Nombre de lignes : 16598
Nombre de colonnes : 12

In [20]:
# Types des variables et valeurs manquantes
display(df.isnull().sum().sort_values(ascending=False))

# Nombre de doublons
print("Doublons :", df.duplicated().sum())

Year                271
Publisher            58
Name                  0
Rank                  0
Platform              0
Genre                 0
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Categorie owners      0
dtype: int64

Doublons : 0

In [17]:
# Statistiques descriptives
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Rank,16598.0,NaN,NaN,NaN,8300.605254,4791.853933,1.0,4151.25,8300.5,12449.75,16600.0
Name,16598,11493,Need for Speed: Most Wanted,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Platform,16598,31,DS,2163,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,16327.0,NaN,NaN,NaN,2006.406443,5.828981,1980.0,2003.0,2007.0,2010.0,2020.0
Genre,16598,12,Action,3316,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Publisher,16540,578,Electronic Arts,1351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NA_Sales,16598.0,NaN,NaN,NaN,0.264667,0.816683,0.0,0.0,0.08,0.24,41.49
EU_Sales,16598.0,NaN,NaN,NaN,0.146652,0.505351,0.0,0.0,0.02,0.11,29.02
JP_Sales,16598.0,NaN,NaN,NaN,0.077782,0.309291,0.0,0.0,0.0,0.04,10.22
Other_Sales,16598.0,NaN,NaN,NaN,0.048063,0.188588,0.0,0.0,0.01,0.04,10.57
Global_Sales,16598.0,NaN,NaN,NaN,0.537441,1.555028,0.01,0.06,0.17,0.47,82.74
Categorie owners,16598,6,<1 000,5730,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:

# Définir les limites des 5 catégories
limites = [
    -1,0.001, 0.01, 0.1, 1,
    20, float("inf")
]

noms = [
    "<1 000",
    "1 000-10 000",
    "10 000-100 000 ",
    "100 000-1M",
    "1M-20M",
    "20M<"
]

# Attribuer une catégorie à chaque jeu
df["Categorie owners"] = pd.cut(
    df["EU_Sales"],
    bins=limites,
    labels=noms
)

df["Categorie owners"].value_counts(normalize=True) * 100

Categorie owners
<1 000             34.522232
10 000-100 000     30.750693
100 000-1M         22.882275
1 000-10 000        9.013134
1M-20M              2.825642
20M<                0.006025
Name: proportion, dtype: float64

In [28]:
# Supprimer les lignes contenant au moins une valeur manquante
df = df.dropna()

# Supprimer les lignes où EU_Sales vaut 0
df = df[df["EU_Sales"] != 0]

# Réinitialiser les index
df = df.reset_index(drop=True)

# Vérifier le résultat
print("Dimensions du dataset :", df.shape)
print("Valeurs manquantes restantes :", df.isnull().sum().sum())
print("Nombre de jeux avec EU_Sales = 0 :", (df["EU_Sales"] == 0).sum())

Dimensions du dataset : (10667, 12)
Valeurs manquantes restantes : 0
Nombre de jeux avec EU_Sales = 0 : 0